---

OS_USER: ubuntu

# common_django_project, common_django_static
DJANGO_PROJECT_PATH_PARENT:  "/home/ubuntu/geodash-server.git"

# common_venv
VENV_NAME: geodash
VENV_PATH: "/home/ubuntu/.venvs/geodash"

DATABASE_ACL:
  - regexp: "local {{ DB_NAME }} {{ DB_USER }} md5"
    line: "local {{ DB_NAME }} {{ DB_USER }} md5"
    state: present
  - regexp: "host {{ DB_NAME }} {{ DB_USER }} 127.0.0.1/32 md5"
    line: "host {{ DB_NAME }} {{ DB_USER }} 127.0.0.1/32 md5"
    state: present

DATABASE_LISTEN_ADDRESSES:
  - "*"

GUNICORN_BIND: "127.0.0.1:8000"

GIT_REPOS:
  - src: git://github.com/geodashio/geodash-server.git
    dest: /home/ubuntu/geodash-server.git
    version: HEAD
  - src: git://github.com/geodashio/geodash-framework-django.git
    dest: /home/ubuntu/geodash-framework-django.git
    version: HEAD
  - src: git://github.com/geodashio/geodash-base.git
    dest: /home/ubuntu/geodash-base.git
    version: HEAD

# common_editable
COMMON_EDITABLE_PACKAGES:
  - name: geodash-server
    parent: /home/ubuntu
    path: geodash-server.git
  - name: geodash-framework-django
    parent: /home/ubuntu
    path: geodash-framework-django.git

# common_django_static
STATIC_DEVELOPMENT: true
