---

- assert:
    that:
      - VENV_NAME != ''
      - VENV_PATH != ''
  tags: ['check_vars']

- set_fact:
    venv_config: '~/.bash_aliases'
  when: ansible_os_family == "Debian"

- set_fact:
    venv_config: '~/.bashrc'
  when: ansible_os_family == "RedHat"

- name: "Add Virtual Environment Comands to .bash_aliases"
  lineinfile:
    dest: "{{ venv_config }}"
    line: "{{ item }}"
    create: "yes"
  with_items:
    - "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python"
    - "export WORKON_HOME=~/.venvs"
    - "source /usr/local/bin/virtualenvwrapper.sh"
    - "export PIP_DOWNLOAD_CACHE=$HOME/.pip-downloads"

- name: "Create Virtual Environment {{ VENV_NAME }}"
  #command: "virtualenv {{ VENV_NAME }} -p python2.7 creates={{ VENV_PATH }}"
  command: "virtualenv -p python2.7 {{ VENV_PATH }}"
  register: venv_result
  #changed_when: venv_result.rc
  changed_when: true
  failed_when: false
