---
- assert:
    that:
      - GDAL_VERSION != ''
      - VENV_PATH != ''
  tags: ['check_vars']

- name: "GDAL Python Bindings / Requirement Check"
  shell: "{{ VENV_PATH }}/bin/pip list | grep \"^GDAL ({{ GDAL_VERSION }})$\""
  ignore_errors: yes
  register: gdal_present
  changed_when: False
  failed_when: False
  tags: ['check_gdal']

- include: gdal.yml
  when: gdal_present.rc == 1
