---

- assert:
    that:
      - DB_NAME != ''
      - DB_USER != ''
      - DB_PASS != ''
  tags: ['check_vars']

- name: "Common DB Init / Ensure the PostgreSQL service is running"
  service: name=postgresql state=started enabled=yes

- name: "Common DB Init / Create User"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ DB_USER }}"
    password: "{{ DB_PASS }}"
    encrypted: true

- name: "Common DB Init / Create Database"
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ DB_NAME }}"
    encoding: 'UTF8'
    template: template_postgis
    owner: "{{ DB_USER }}"

- name: "Common DB Init / Grant All Privileges to {{ DB_USER }}"
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ DB_NAME }}"
    role: "{{ DB_USER }}"
    privs: ALL
    type: schema
    objs: public
