---

# common_db_init, common_db_security, common_db_install_ubuntu
DATABASE_APT_PACKAGE: postgresql-9.5-postgis-2.2
PATH_PG_HBA: "/etc/postgresql/9.5/main/pg_hba.conf"
PATH_PG_CONF: "/etc/postgresql/9.5/main/postgresql.conf"

PACKAGES_JAVA:
  - "openjdk-8-jdk"

ALTERNATIVE_JAVA: "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
