---

- name: "Add Node.js repo"
  become: yes
  become_user: root
  apt_repository: repo="ppa:chris-lea/node.js" state=present

- name: Install Other Libraries
  become: yes
  become_user: root
  apt: name="{{ item }}" state=latest
  with_items:
    - nodejs

- name: Install NPM Libraries
  become: yes
  become_user: root
  npm: name="{{ item }}" state=latest global=yes
  with_items:
    - bower
    - grunt-cli
