---

- name: Creates a base Ubuntu development virtual machine
  hosts: all
  remote_user: vagrant

  roles:
    - common_base_ubuntu  # Installs basic libraries, including GCC, PIP
    - common_java_ubuntu # Installs Java
    - common_db_install_ubuntu # Installs PostGIS Server and Database Tempaltes
